spring.application.name=HDD-T1-RS-GE-BH
spring.mongodb.uri=mongodb://localhost:27017/hddt1rsgebh

sansaweigh.api.url=http://localhost:3006/api/v1/scales

spring.jackson.property-naming-strategy=SNAKE_CASE