package cl.usm.hddt1rsgebh.services;

import cl.usm.hddt1rsgebh.entities.Shipment;
import cl.usm.hddt1rsgebh.entities.ShipmentRequest;
import cl.usm.hddt1rsgebh.entities.Status;
import cl.usm.hddt1rsgebh.entities.WeightCategory;
import cl.usm.hddt1rsgebh.exceptions.IllegalWeighingStateException;
import cl.usm.hddt1rsgebh.integration.ExternalScaleClient;
import cl.usm.hddt1rsgebh.repositories.ShipmentRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.List;

@Service
public class ShipmentService {
    private static final Logger log = LoggerFactory.getLogger(ShipmentService.class);

    private final ExternalScaleClient client;
    private final ShipmentRepository shipmentRepository;

    @Autowired
    public ShipmentService(ExternalScaleClient client, ShipmentRepository shipmentRepository) {
        this.client = client;
        this.shipmentRepository = shipmentRepository;
    }

    public boolean createShipment(ShipmentRequest shipmentRequest){
        try {
            Shipment shipment = new Shipment(
                    null, // id, generated by mongo
                    shipmentRequest.getScaleId(),
                    shipmentRequest.getPackageId(),
                    kgToSa(shipmentRequest.getWeight()),
                    getWeightCategory(shipmentRequest.getWeight()),
                    Status.INGRESADO,
                    Instant.now()
            );

            shipmentRepository.save(shipment);
            return true;
        } catch (DataAccessException e) {
            log.error("Failed to save shipment for package {}", shipmentRequest.getPackageId(), e);
            return false;
        }
    }

    /*
     * transitions a shipment to the target status after validating the
     * domain rules (see validateTransition); throws
     * IllegalWeighingStateException when a rule is violated.
     */
    public boolean updateShipment(Shipment shipment, Status target){
        validateTransition(shipment, target); // just throw. the calling function will catch it if it errors
        try {
            shipment.setStatus(target);
            shipment.setUpdatedAt(Instant.now());
            shipmentRepository.save(shipment);
            return true;
        } catch (DataAccessException e) {
            log.error("Failed to update shipment {}", shipment.getId(), e);
            return false;
        }
    }

    private static final ZoneId ZONE = ZoneId.of("America/Santiago");

    /*
     * validates a status transition against the domain rules:
     *  rule 1: the flow must be INGRESADO -> PESADO -> APROBADO/RECHAZADO -> DESPACHADO
     *  rule 2: cannot weigh heavy packages between 20:00 and 06:00
     *  rule 3: if the scale id is prime, cannot weigh heavy packages on odd days
     * throws IllegalWeighingStateException when a rule is violated.
     */
    private void validateTransition(Shipment shipment, Status target){
        Status current = shipment.getStatus();

        // rule 1: the registered -> weighed -> accepted/rejected -> sent flow,
        // walkable in either direction to correct mistakes
        if (!isAllowedTransition(current, target)){
            throw new IllegalWeighingStateException(
                    "Invalid status transition: " + current + " -> " + target);
        }

        // rules 2 and 3 only constrain weighing a heavy package
        boolean weighingHeavy = target == Status.PESADO
                && shipment.getWeightCategory() == WeightCategory.PESADO;
        if (!weighingHeavy){
            return;
        }

        ZonedDateTime now = ZonedDateTime.now(ZONE);

        // rule 2: no heavy weighing between 20:00 (inclusive) and 06:00 (exclusive)
        int hour = now.getHour();
        if (hour >= 20 || hour < 6){
            throw new IllegalWeighingStateException(
                    "Cannot weigh heavy packages between 20:00 and 06:00");
        }

        // rule 3: prime scale id cannot weigh heavy packages on odd days
        if (isPrime(parseScaleId(shipment.getScaleId())) && now.getDayOfMonth() % 2 != 0){
            throw new IllegalWeighingStateException(
                    "Scale " + shipment.getScaleId()
                            + " cannot weigh heavy packages on odd days (prime scale id)");
        }
    }

    // a transition is allowed if it is a forward step in the flow or its reverse
    private boolean isAllowedTransition(Status current, Status target){
        if (current == null || target == null || current == target){
            return false;
        }
        return isForwardStep(current, target) || isForwardStep(target, current);
    }

    private boolean isForwardStep(Status from, Status to){
        return switch (from) {
            case INGRESADO -> to == Status.PESADO;
            case PESADO -> to == Status.APROBADO || to == Status.RECHAZADO;
            case APROBADO, RECHAZADO -> to == Status.DESPACHADO;
            case DESPACHADO -> false;
        };
    }

    // scale ids are stored as strings; non-numeric ids simply cannot be prime
    private Double parseScaleId(String scaleId){
        try {
            return Double.parseDouble(scaleId);
        } catch (NumberFormatException | NullPointerException e) {
            return null;
        }
    }

    public Shipment getShipmentById(String id){
        return shipmentRepository.findById(id).orElse(null);
    }

    public List<Shipment> getShipmentsByDate(LocalDate date){
        ZoneId zone = ZoneId.of("America/Santiago");

        // currently same day, can be expanded to use wider ranges
        Instant start = date.atStartOfDay(zone).toInstant();
        Instant end = date.plusDays(1).atStartOfDay(zone).toInstant();

        return shipmentRepository.findByUpdatedAtBetween(start, end);
    }

    // 1 Sansa (Sa) = 1.337 Kg
    public double saToKg(double sa){
        return sa/1.337;
    }

    public double kgToSa(double kg){
        return kg*1.337;
    }

    // claude's work
    public boolean isPrime(Double input){
        if (input == null || input != Math.floor(input) || Double.isInfinite(input)) {
            return false;
        }

        long n = input.longValue();
        if (n < 2) { return false; }
        if (n < 4) { return true; }          // 2 and 3 are prime
        if (n % 2 == 0) { return false; }

        for (long i = 3; i * i <= n; i += 2) {
            if (n % i == 0) { return false; }
        }
        return true;
    }

    private WeightCategory getWeightCategory(Double kg){
        double sa = kgToSa(kg);

        if (sa <= 10){ return WeightCategory.LIVIANO; }
        if (sa <= 50){ return WeightCategory.MEDIANO; }
        return WeightCategory.PESADO;
    }
}
